services:
  survival:
    image: itzg/minecraft-server:java24
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      ONLINE_MODE: "FALSE"
      VERSION: "1.21.8"
      ENABLE_WHITELIST: "TRUE"
      SPAWN_PROTECTION: "32"
      MODRINTH_PROJECTS: |
        fabric-api
        fabricproxy-lite
        simple-voice-chat
        sleep
        factions
      OPS: |
        cheesemany
    volumes:
      - ./volumes/survival_data:/data

  proxy:
    image: itzg/mc-proxy:java24
    environment:
      TYPE: "VELOCITY"
      DEBUG: "false"
      ENABLE_RCON: "true"
      MINECRAFT_VERSION: "1.21.8"
      MODRINTH_PROJECTS: |
        simple-voice-chat:velocity-2.6.4
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    volumes:
      - ./velocity.toml:/config/velocity.toml:ro
      - ./forwarding.secret:/config/forwarding.secret:ro
      - ./volumes/proxy_data:/server

